### PR TITLE
chore(deps): bump github.com/knadh/koanf to v2.0.1

### PR DESCRIPTION
**Pull request by kralicky**
## Related Issue or Design Document

This updates `github.com/knadh/koanf` from v1.4.4 to v2.0.1. There are no functional changes, but the module structure was reworked to have several submodules where there were previously packages within one main module.

The dependency of koanf v1 in this package is causing an issue for a module of mine that imports both koanf/v2 and a different ory package (which imports this one) because there is a new submodule in koanf/v2 with the same name as a package in v1. Go does not know how to resolve this, and it throws the following error:
```
error while importing github.com/knadh/koanf/v2: ambiguous import: found package github.com/knadh/koanf/maps in multiple modules:
	github.com/knadh/koanf v0.14.1-0.20201201075439-e0853799f9ec (/home/joe/go/pkg/mod/github.com/knadh/koanf@v0.14.1-0.20201201075439-e0853799f9ec/maps)
	github.com/knadh/koanf/maps v0.1.1 (/home/joe/go/pkg/mod/github.com/knadh/koanf/maps@v0.1.0)
```

Replacing ory/x with my fork solves the problem.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
This requires adopting the koanf changes in these other projects as well:

- http://github.com/ory/kratos
- http://github.com/ory/keto
- http://github.com/ory/hydra
- http://github.com/ory/oathkeeper

If it works there, we can merge this :)

**Comment by kralicky** [comment]
@aeneasr Great - I'll do the same update for those repos as well, and link them here.

**Comment by kralicky** [comment]
Each repo's go.mod contains a replacement to my fork of ory/x, which should allow it to build and run tests to see if they pass. I suppose we would have to merge this PR first and then edit the other ones to remove the replacement? Not sure, up to you.

**Comment by aeneasr** [comment]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Comment by aeneasr** [comment]
Could you update the PRs in the individual repos now with the official ory/x version? :) Thank you! 👍

**Comment by kralicky** [comment]
Updated the other PRs to import ory/x@master. :+1:

**Comment by kralicky** [comment]
I also went ahead and updated fosite as well (that's the library I'm using directly). Let me know if those changes look good. I made my best guess on some updates to error-related test cases.

**Pull request merged**
