### PR TITLE
feat: GELF support 

### PR DESCRIPTION
**Pull request by fjvierap**
@aeneasr I noticed than previous formatter has an issue as it trades data["level"] = entry.Level as string... where it should be an integer as https://docs.graylog.org/en/3.2/pages/gelf.html 

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you - wouldn't it make sense to fix that in upstream instead of forking the code here?

**Comment by fjvierap** [comment]
yes... let me create a PR in https://github.com/seatgeek/logrus-gelf-formatter/blob/master/gelf_log_formatter.go I will update you @aeneasr

**Comment by aeneasr** [comment]
Awesome, thank you  @fjvierap !

**Comment by fjvierap** [comment]
@aeneasr PR update with latest https://github.com/seatgeek/logrus-gelf-formatter please check when you can

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Pull request merged**
