### PR TITLE
feat: Add Zipkin support

### PR DESCRIPTION
**Pull request by timsazon**
## Related issue

https://github.com/ory/hydra/issues/1903

## Proposed changes

Add Zipkin tracer support (`github.com/openzipkin/zipkin-go` with opentracing wrapper `github.com/openzipkin-contrib/zipkin-go-opentracing`)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you! This looks great.

How can we assure that the code is actually working the way it should? Would it be possible to supply tests?

**Comment by timsazon** [comment]
> Thank you! This looks great.
> 
> How can we assure that the code is actually working the way it should? Would it be possible to supply tests?

I've added tests for Zipkin but not Jaeger (it works through UDP agent so it is quite difficult to test)

**Comment by aeneasr** [comment]
Awesome! Thank you!

**Comment by aeneasr** [comment]
Released as v0.0.130 - you can now update the hydra pr :)

**Pull request merged**
