### PR TITLE
fix(clidoc): sidebar spam

### PR DESCRIPTION
**Pull request by zepatrik**
Regression of the sidebar spam bug. Looks like this was caused because of a change to the sidebar file format. Added a snapshot test.

### CODE REVIEW

**Comment by aeneasr** [comment]
Tests fail

**Comment by zepatrik** [comment]
Right, this is because of https://github.com/tidwall/pretty/issues/11

**Comment by zepatrik** [comment]
Ah no it was because `filepath` was used instead of `path` (which failed the windows test). Linux was just flaky.

**Comment by zepatrik** [comment]
And also `\r\n` line endings :sob:

**Review by aeneasr — APPROVED** [review]

**Pull request merged**
