### PR TITLE
feat: upgrade OTEL

### PR DESCRIPTION
**Pull request by vivshankar**
Given the request made in ory/fosite#809, this PR proposes upgrading the OTEL modules to the latest version (v1.29.0).

## Related Issue or Design Document

ory/fosite#809

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

N/A

### CODE REVIEW

**Review by srisuman — APPROVED** [review]

**Review by zepatrik — APPROVED** [review]

**Comment by vivshankar** [comment]
@alnr I have tested with Fosite's unit tests and haven't seen any issues. I have not tried this with Hydra or the other products. I don't have those running locally.

**Comment by alnr** [comment]
I don't have capacity right now to verify this doesn't cause upgrade issues in kratos/keto/hydra/oathkeeper.

**Comment by vivshankar** [comment]
Interestingly, Hydra is already at v1.28 - https://github.com/ory/hydra/blob/master/go.mod#L60C2-L63C40

**Comment by alnr** [comment]
bumped in v0.0.672

**Pull request closed without merging**
