### PR TITLE
feat: Instana support

### PR DESCRIPTION
**Pull request by dadrus**
## Related issue

@aeneasr: This is for #348 

## Proposed changes

Since Instana supports setting everything via [environment variables](https://www.instana.com/docs/reference/environment_variables/#language-sensors), the current implementation simply makes use of this possibility. 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

As soon as this PR is merged, I'll open PRs for hydra and kratos to make use of it.

### CODE REVIEW

**Comment by dadrus** [comment]
Since instana is a pure SaaS, I struggle to add usable tests.

**Comment by aeneasr** [comment]
Maybe the tests could follow those of e.g. AWS X-Ray or DataDog?

**Comment by dadrus** [comment]
I'll take a look

**Comment by dadrus** [comment]
@aeneasr: FMPOV this PR is complete.

**Review by aeneasr — APPROVED** [review]

**Pull request merged**
